[project]
name = "simplellm"
version = "0.0.2"
authors = [
  { name="Nikolay Blagoev", email="nickyblagoev@gmail.com" },
]
description = "Build LLMs easily"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/NikolayBlagoev/simplellm"
Issues = "https://github.com/NikolayBlagoev/simplellm/issues"